### ISSUE TITLE
Permission to create a fabric port?

### ISSUE THREAD

**Issue by williamk-jr** [Voxla/midnightlurker#13]
Sorry if this isn’t the best place for this, but I’m a Fabric modder speaking permission to port this mod to fabric and publish it. If you do not wish me to, I completely respect that and will not press any further.

**Comment by Voxla** [comment]
Yes, you can port this mod to fabric if you want.

**Comment by williamk-jr** [comment]
Ok, cool, I'll make sure to credit this this mod when I finish!
