### ISSUE TITLE
I can't hit the Lurker

### ISSUE THREAD

**Issue by CaraMob323** [Voxla/midnightlurker#14]
I can't hit him or do anything to him. When aggressive mode appears, it hits us until it disappears for a few minutes and it is very annoying not to be able to hit it.

Here is my modlist:
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Stack Refill (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/stack-refill)
[BraincellAPI (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/braincellapi)
[Realm RPG: Pots & Mimics (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/pots-and-mimics-rpg)
[Too Fast (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/too-fast)
[Repurposed Structures (Neoforge/Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[Nightmare Craft: Mobs (by divinegaminginc)](https://www.curseforge.com/minecraft/mc-mods/nightmare-craft-mobs)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Awesome Dungeon - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-forge)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Adaptive Performance Tweaks: Core (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Dynamic Trees (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)
[Adaptive Performance Tweaks: Spawn (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-spawn)
[Dungeons Mobs (by the_infamous_1)](https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs)
[Apocalypse Weapons (by brska)](https://www.curseforge.com/minecraft/mc-mods/aw)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Scary Mobs And Bosses (by ALe96)](https://www.curseforge.com/minecraft/mc-mods/scary-mobs-and-bosses)
[Cave Dweller Reimagined (by idk_someguy)](https://www.curseforge.com/minecraft/mc-mods/cave-dweller-reimagined)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[UnionLib (by Stereowalker)](https://www.curseforge.com/minecraft/mc-mods/unionlib)
[Dungeons Libraries (by Patrigan)](https://www.curseforge.com/minecraft/mc-mods/dungeons-libraries)
[ItemPhysic Full (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/itemphysic)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Distant Friends (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/distant-friends)
[Mystical Agriculture (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Creatures and Beasts (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Simple Tomb (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/simple-tomb)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Entity Collision FPS Fix (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[ExpandAbility (by florensie)](https://www.curseforge.com/minecraft/mc-mods/expandability)
[Dungeons & More Mod (by NachoElPela8)](https://www.curseforge.com/minecraft/mc-mods/dungeons-more-mod)
[Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)
[Brass's Armory (by jodlodi)](https://www.curseforge.com/minecraft/mc-mods/brass-armory)
[Majrusz Library (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majrusz-library)
[Farming for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads)
[OfflineSkins (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/offlineskins)
[Dynamic Surroundings Resurrected (by 100media)](https://www.curseforge.com/minecraft/mc-mods/dynamic-surrounding-resurrected)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Whisperwoods (by itsmeowdev)](https://www.curseforge.com/minecraft/mc-mods/whisperwoods)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Traveler's Backpack (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Dynamic Trees - Quark (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[project-333256 (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/project-333256)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Big Brain (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/big-brain)
[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)
[ProjectE (by SinKillerJ)](https://www.curseforge.com/minecraft/mc-mods/projecte)
[⚔️ RPG style More Weapons! (by zrikon)](https://www.curseforge.com/minecraft/mc-mods/rpg-style-more-weapons)
[Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Untamed Wilds (by raytrace82)](https://www.curseforge.com/minecraft/mc-mods/untamedwilds)
[Rotten Creatures (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Age of Weapons (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/age-of-weapons)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[The Pure Suffering Mod (by TheAGamePlayer)](https://www.curseforge.com/minecraft/mc-mods/the-pure-suffering-mod)
[Extra Armor (by Bailym)](https://www.curseforge.com/minecraft/mc-mods/extra-armor)
[Herd Mentality (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/herd-mentality)
[Max Health Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Feature NBT Deadlock Be Gone (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone)
[Overloaded Armor Bar (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lendercataclysm)
[Champions (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/champions)
[Savage & Ravage (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage)
[Invocore (Code Library) (by Cycro54)](https://www.curseforge.com/minecraft/mc-mods/invocore-utility-mod)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Danny's Expansion (by BottomTextDanny)](https://www.curseforge.com/minecraft/mc-mods/dannys-expansion)
[Adaptive Performance Tweaks: Items (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-items)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Pig Pen Cipher (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Iter RPG (by AcmaKurihara)](https://www.curseforge.com/minecraft/mc-mods/iter-rpg)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Falling Leaves (Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[The Man From The Fog (by M_Productions)](https://www.curseforge.com/minecraft/mc-mods/the-man-from-the-fog)
[Dark Utilities (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Randomium Ore (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/randomium-ore)
[Adaptive Performance Tweaks: Mods (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-mods)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Dynamic Trees - Biomes O' Plenty (by cadaverous_queen)](https://www.curseforge.com/minecraft/mc-mods/dtbop)
[Water Strainer (by Ruuubi)](https://www.curseforge.com/minecraft/mc-mods/water-strainer)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs)
[The Midnight Lurker (by Voxla)](https://www.curseforge.com/minecraft/mc-mods/the-midnight-lurker)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
[Sons Of Sins (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/sons-of-sins)
[Radon (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radon)
[InsaneLib (by Insane96)](https://www.curseforge.com/minecraft/mc-mods/insanelib)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[MapFrontiers (by meme_sapiens)](https://www.curseforge.com/minecraft/mc-mods/mapfrontiers)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[JEITweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/jeitweaker)
[ArmoreableMobs (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/armoreablemobs)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Dynamic Trees + (by MaxHyper)](https://www.curseforge.com/minecraft/mc-mods/dynamictreesplus)
[Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
[Brutal Bosses - Custom Bosses[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon)
[Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Monster Plus (by Nitespring)](https://www.curseforge.com/minecraft/mc-mods/monster-plus)
[Lava Monsters (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/lava-monsters)
[Eyes in the Darkness (by gigaherz)](https://www.curseforge.com/minecraft/mc-mods/eyes-in-the-darkness)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Pipez (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/pipez)
[TenshiLib (Forge) (by flemmli97)](https://www.curseforge.com/minecraft/mc-mods/tenshilib)
[Bad Mobs (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bad-mobs)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Born in Chaos (by mongoose_artist)](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos)

**Comment by Voxla** [comment]
I would suggest checking the config of the mod. There is an option in there called "lurker_invulnerable", and if it is set to "true", then he won't be able to be hit. Just set it to "false", and it should fix the problem you're having. The config is in the game directory folder inside the "config" folder, and the config file itself is called "midnightlurkerconfig.json". You can edit it with Notepad or any software you have on your computer that can edit code, just in case you didn't know.

However, if it's already set to "false" in the config, then I'd have to try and recreate the problem, as I don't have this problem when testing or playing the mod myself.

**Comment by CaraMob323** [comment]
> I would suggest checking the config of the mod. There is an option in there called "lurker_invulnerable", and if it is set to "true", then he won't be able to be hit. Just set it to "false", and it should fix the problem you're having. The config is in the game directory folder inside the "config" folder, and the config file itself is called "midnightlurkerconfig.json". You can edit it with Notepad or any software you have on your computer that can edit code, just in case you didn't know.
> 
> However, if it's already set to "false" in the config, then I'd have to try and recreate the problem, as I don't have this problem when testing or playing the mod myself.

Yes, that was it. Thank you so much
