### ISSUE TITLE
My game keeps crashing every time the Lurker attacks me and (probably) jumpscares me

### ISSUE THREAD

**Issue by LordyZa** [Voxla/midnightlurker#15]
Here's both my logs, crash log and game log. 

[crash-2024-04-28_01.29.50-server.txt](https://github.com/Voxla/midnightlurker/files/15141287/crash-2024-04-28_01.29.50-server.txt)

[latest.log](https://github.com/Voxla/midnightlurker/files/15141288/latest.log)

**Comment by Voxla** [comment]
Strange... perhaps another mod could be conflicting with my mod? though I don't see another mod being mentioned in the crash, so I don't know.

I'm not sure why it would crash when the Lurker attacks you. Also, I don't have this problem when playing or testing the mod myself.

And the only thing I see in the crash log that is really mentioned is the Void Gateway, which has nothing to do with you being attacked.

If you have other mods installed with my mod, could I possibly have a list to see if I can recreate this issue?

**Comment by LordyZa** [comment]
> Strange... perhaps another mod could be conflicting with my mod? though I don't see another mod being mentioned in the crash, so I don't know.
> 
> I'm not sure why it would crash when the Lurker attacks you. Also, I don't have this problem when playing or testing the mod myself.
> 
> And the only thing I see in the crash log that is really mentioned is the Void Gateway, which has nothing to do with you being attacked.
> 
> If you have other mods installed with my mod, could I possibly have a list to see if I can recreate this issue?

Embeddium dev told me this: 
>the mod just appears to be trying to access client data structures from the server thread, which is not safe (and another mod detects that and blocks it), UWRAD just detects this situation because it would likely cause a random crash somewhere else otherwise

**Comment by LordyZa** [comment]
> Strange... perhaps another mod could be conflicting with my mod? though I don't see another mod being mentioned in the crash, so I don't know.
> 
> I'm not sure why it would crash when the Lurker attacks you. Also, I don't have this problem when playing or testing the mod myself.
> 
> And the only thing I see in the crash log that is really mentioned is the Void Gateway, which has nothing to do with you being attacked.
> 
> If you have other mods installed with my mod, could I possibly have a list to see if I can recreate this issue?

I could send you the modpack if you want, it's quite large

**Comment by mpustovoi** [comment]
Perhaps the MCreator problem, unsolvable at this level

**Comment by Voxla** [comment]
> 
> I could send you the modpack if you want, it's quite large

It would be nice if you could send over the modpack

**Comment by Voxla** [comment]
Actually, I've installed UWRAD and tested it just now, and it might just be UWRAD itself causing the crashing because when I have UWRAD installed, my game seems to crash, and when I don't have UWRAD installed, my game doesn't crash.

I'm not sure if UWRAD is supposed to intentionally crash the game when it detects something wrong or not, but I would assume it's just for crashes in general, so I don't know why it would crash the game when it detects something wrong.
