### ISSUE TITLE
[1.18.2] insanity overlay seems to have a strange interaction with freecam

### ISSUE THREAD

**Issue by veccyboi** [Voxla/midnightlurker#17]
forge: 40.2.14
mods folder: 
![image](https://github.com/Voxla/midnightlurker/assets/85643556/388fced5-64c6-483c-a5a1-19cf253f2b46)

the game crashes when I attempt to exit out of freecam: 
[crash-2024-05-21_17.56.26-client.txt](https://github.com/Voxla/midnightlurker/files/15396134/crash-2024-05-21_17.56.26-client.txt)

from what I can tell, the insanity overlay (with the red vignette and smiling faces) doesn't like freecam.

**Comment by Voxla** [comment]
It seems to have something to do with the sounds of the overlay. I'll try to get this fixed for the next update I put out.
