### ISSUE TITLE
Expection Server tick loop crash.

### ISSUE THREAD

**Issue by Maxi90909** [Voxla/midnightlurker#19]
Game crashes unexpectedly without a warning. I dunno why. I killed the midnight lurker and like 10-20 seconds after it crashed. Please fix. I really enjoy the mod.

[crash-2024-06-16_12.46.29-server.txt](https://github.com/user-attachments/files/15857474/crash-2024-06-16_12.46.29-server.txt)

[latest.log](https://github.com/user-attachments/files/15857477/latest.log)

**Comment by Voxla** [comment]
I couldn't seem to recreate crashing after killing the Lurker, but I think I fixed the problem based on what the crash logs said, so when I publish the next update, it should be fixed, if not just open another issue here or whatever.
