### ISSUE TITLE
Server Ticking

### ISSUE THREAD

**Issue by TheNexopixel** [Voxla/midnightlurker#23]
Hi there, I wanted to use this mod in a modpack (1.18.2)
However, this mod causes intense lags in the form of tick freezes (no idea if this is correct), so the game is practically unplayable. Of course it could be that another mod has problems with this one. Idk
But when I removed this mod, everything ran as normal. Any idea what the problem could be?

PS. The mod is really well done :)

**Comment by Voxla** [comment]
I didn't encounter anything like tick freezing myself while playing around with the mod; however, I did try to fix it even though I couldn't tell if I did, so if you do end up reinstalling the mod or have the newest version installed, do let me know if you're still experiencing this.

**Comment by TheNexopixel** [comment]
I have tried the latest version but I think the problem persists. As I said, there are occasional small lags, which are not extreme, but they disturb the flow of the game. if you haven't noticed anything like this, it could be that the mod has a conflict with another mod. Do you know anything about this?


![image](https://github.com/user-attachments/assets/829775cc-16dd-499e-bb53-adf7c658c9b9)

**Comment by Voxla** [comment]
I think this is fixed? since I uploaded new mod versions in October
If not then just create a new issue
