### ISSUE TITLE
{Suggestion} Make ambience only play when Midnight Lurker has actually spawned somewhere.

### ISSUE THREAD

**Issue by togera13** [Voxla/midnightlurker#4]
I feel the ambience playing randomly in the middle of a peaceful farming session in a fortified base ruins the appeal of turning on the ambience, when I feel it would be far more appropriate for it to play when he has actually spawned somewhere & is an actual tangible threat such as when you are out and about y'know?

I am not saying he needs to attack me while I'm farming just that the ambience needs to not play when there isn't any real action going on & it just kills the mood during the wait for him to spawn since you're always getting the "spooky" music even when he can't do anything & is no-where in sight at that time.

**Comment by Voxla** [comment]
The "spooky" music/ambience is getting changed in the next update to be like this, so if you're somewhere like a city or town or just in an area with lots of light where the Lurker literally can't spawn, it doesn't play ambience.
