### ISSUE TITLE
Midnight lurker spawning to much

### ISSUE THREAD

**Issue by Dcrkie** [Voxla/midnightlurker#7]
I love this mod, but anytime I kill the Midnight lurker, he spawns again and again and again. There was no cool down. It takes numerous attempts to kill him to even have him stop. This mainly happens in the nether, in the overworld i just sleep and he doesnt spawn.

**Comment by Voxla** [comment]
Well, he's supposed to spawn in the Nether regardless of whether you've slept or not, because the Nether isn't the Overworld. However, to deal with him spawning too often, I'll add a config option for the spawning of the Nether version in the next update I do.
